"""phase3_live_engine

Revision ID: 1fcbe0e3ea93
Revises: f78d9fa1fed8
Create Date: 2026-10-05 14:04:51.488737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fcbe0e3ea93'
down_revision: Union[str, Sequence[str], None] = 'f78d9fa1fed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('technical_score', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('communication_score', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('strengths', sa.JSON(), nullable=True))
    op.add_column('evaluations', sa.Column('weaknesses', sa.JSON(), nullable=True))
    op.add_column('interview_sessions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interview_sessions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'completed_at')
    op.drop_column('interview_sessions', 'started_at')
    op.drop_column('evaluations', 'weaknesses')
    op.drop_column('evaluations', 'strengths')
    op.drop_column('evaluations', 'communication_score')
    op.drop_column('evaluations', 'technical_score')
    # ### end Alembic commands ###
