"""ai_engine_phase2

Revision ID: f78d9fa1fed8
Revises: 8db964790638
Create Date: 2026-10-05 13:53:40.623167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78d9fa1fed8'
down_revision: Union[str, Sequence[str], None] = '8db964790638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('ai_score', sa.Float(), nullable=True))
    op.add_column('answers', sa.Column('ai_strengths', sa.JSON(), nullable=True))
    op.add_column('answers', sa.Column('ai_weaknesses', sa.JSON(), nullable=True))
    op.add_column('answers', sa.Column('ai_feedback', sa.String(), nullable=True))
    op.add_column('evaluations', sa.Column('overall_score', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('final_report', sa.String(), nullable=True))
    op.add_column('evaluations', sa.Column('recommendation', sa.String(length=100), nullable=True))
    op.add_column('interviews', sa.Column('job_description', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('skills', sa.String(length=1000), nullable=True))
    op.add_column('interviews', sa.Column('difficulty', sa.String(length=50), nullable=True))
    op.add_column('interviews', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('blueprint', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('topic', sa.String(length=255), nullable=True))
    op.add_column('questions', sa.Column('difficulty', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('expected_points', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('question_type', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('is_dynamic', sa.Boolean(), nullable=False))
    op.add_column('questions', sa.Column('session_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'questions', 'interview_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'session_id')
    op.drop_column('questions', 'is_dynamic')
    op.drop_column('questions', 'question_type')
    op.drop_column('questions', 'expected_points')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'topic')
    op.drop_column('interviews', 'blueprint')
    op.drop_column('interviews', 'duration_minutes')
    op.drop_column('interviews', 'difficulty')
    op.drop_column('interviews', 'skills')
    op.drop_column('interviews', 'job_description')
    op.drop_column('evaluations', 'recommendation')
    op.drop_column('evaluations', 'final_report')
    op.drop_column('evaluations', 'overall_score')
    op.drop_column('answers', 'ai_feedback')
    op.drop_column('answers', 'ai_weaknesses')
    op.drop_column('answers', 'ai_strengths')
    op.drop_column('answers', 'ai_score')
    # ### end Alembic commands ###
